#!/usr/bin/env bash
# displays the time for 12 hours and 59 mins.
hours=0
while [ $hours -lt 13 ]
do
echo "Hour: $hours"
mins=1
while [ $mins -lt 60 ]
do
echo $mins
let mins+=1
done
let hours+=1
done
